# See 'settings.example.yml' for help.
# 查看'settings.example.yml'文件以获取帮助。

language: zh_CN
maxRegPerIP: 2
maxOnlinePerIP: 2
forceStandardPlayerName: true
minPlayerNameLength: 2
maxPlayerNameLength: 15
noDamageBeforeLogin: true
rejoinInterval: 3
backAfterLogin: true
noMoveBeforeLogin: true
commandWhitelist:
  - /(?i)l(ogin)?(\z| .*)
  - /(?i)reg(ister)?(\z| .*)
  - /(?i)resetpassword?(\z| .*)
  - /(?i)repw?(\z| .*)
  - /(?i)worldedit cui
loginTimeout: 120
saveDeadPlayerLogoutLocation: true
forceStrongPassword: true
maxPasswordLength: 16
